# Generated by Django 4.2.2 on 2024-08-31 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("diary", "0002_alter_diary_image_alter_diary_image_cover"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="diary",
            options={
                "ordering": ["-created_at", "topic"],
                "verbose_name": "Дневник",
                "verbose_name_plural": "Дневники",
            },
        ),
    ]
