# Generated by Django 4.2.2 on 2024-09-03 07:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("diary", "0004_diary_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="diary",
            name="author",
            field=models.ForeignKey(
                blank="True",
                null="True",
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Автор",
            ),
        ),
    ]
